name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # deploy when you push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or whatever your project needs

    - name: Install dependencies
      run: npm install

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v1
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}" # GitHub automatically provides this
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
