- name: Deploy to Firebase Hosting
  uses: FirebaseExtended/action-hosting-deploy@v0.10.0
  with:
    repoToken: ${{ secrets.GITHUB_TOKEN }}
    firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
