name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Firebase CLI (latest version)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # Step 3: Authenticate with Firebase using the service account
      - name: Authenticate to Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-service-account.json
          firebase login:ci --token "$(firebase login:ci)"
        # Note: With FirebaseExtended/action-hosting-deploy this token step is optional,
        # the service account secret is enough

      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.10.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for PR comments
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: linkbotlabs
          channelId: live  # change to a preview channel if needed
